apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jitsutest
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: jitsutest
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://jitsutest.ansatt.nav.no"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  liveness:
    path: "/api/healthcheck"
    port: 3000
    initialDelay: 60
  readiness:
    path: "/api/healthcheck"
    port: 3000
    initialDelay: 30
  replicas:
    cpuThresholdPercentage: 50
    max: 2
    min: 1
  port: 3000
  env:
    - name: MIT_COMPLIANT
      value: "false"
    - name: ENABLE_CREDENTIALS_LOGIN
      value: "true"
    - name: SYNCS_ENABLED
      value: "false"
    - name: FORCE_UPDATE_DB
      value: "true"
    - name: SEED_USER_EMAIL
      value: "eilif.johansen@nav.no"
    - name: SEED_USER_PASSWORD
      value: "test"
    - name: ROTOR_URL
      value: "http://rotor:3401"
    - name: ROTOR_AUTH_KEY
      value: "default"
    - name: BULKER_URL
      value: "http://bulker:3042"
    - name: CONSOLE_RAW_AUTH_TOKENS
      value: "default"
    - name: BULKER_AUTH_KEY
      value: "default"
    - name: DATABASE_URL
      value: "$(NAIS_DATABASE_JITSUTEST_JITSUTEST_URL)"
    - name: SYNCCTL_URL
      value: "http://syncctl:3043"
    - name: SYNCCTL_AUTH_KEY
      value: "default"
    - name: JITSU_INGEST_PUBLIC_URL
      value: "http://localhost:8080/"
    - name: JITSU_PUBLIC_URL
      value: "https://jitsutest.ansatt.nav.no/"
    - name: NEXTAUTH_URL
      value: "https://jitsutest.ansatt.nav.no/"
    - name: CLICKHOUSE_HOST
      value: "clickhouse:8123"
    - name: CLICKHOUSE_PASSWORD
      value: "default"
    - name: CLICKHOUSE_DATABASE
      value: "newjitsu_metrics"
    - name: MONGODB_URL
      value: "mongodb://default:default@mongo/"
    - name: MONGODB_NETWORK_COMPRESSION
      value: "none"
