apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jitsutest
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  ingresses:
    - "https://jitsutest.ansatt.nav.no"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  liveness:
    path: "/signin"
    port: 3000
  readiness:
    path: "/signin"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 2
    min: 1
  port: 3000
