apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jitsutest
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  ingresses:
    - "https://jitsutest.ansatt.nav.no"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  liveness:
    path: "/api/healthcheck"
    port: 3000
    initialDelay: 60
  readiness:
    path: "/api/healthcheck"
    port: 3000
    initialDelay: 30
  replicas:
    cpuThresholdPercentage: 50
    max: 2
    min: 1
  port: 3000
  env:
    - name: MIT_COMPLIANT
      value: "false"
    - name: ENABLE_CREDENTIALS_LOGIN
      value: "true"
    - name: SYNCS_ENABLED
      value: "false"
    - name: FORCE_UPDATE_DB
      value: "true"
