#!/bin/bash

# Construct DATABASE_URL with basic PostgreSQL connection
if [[ -n "$NAIS_DATABASE_JITSUTEST_JITSUTEST_USERNAME" && -n "$NAIS_DATABASE_JITSUTEST_JITSUTEST_PASSWORD" && -n "$NAIS_DATABASE_JITSUTEST_JITSUTEST_HOST" && -n "$NAIS_DATABASE_JITSUTEST_JITSUTEST_PORT" && -n "$NAIS_DATABASE_JITSUTEST_JITSUTEST_DATABASE" ]]; then
  export DATABASE_URL="postgresql://$NAIS_DATABASE_JITSUTEST_JITSUTEST_USERNAME:$NAIS_DATABASE_JITSUTEST_JITSUTEST_PASSWORD@$NAIS_DATABASE_JITSUTEST_JITSUTEST_HOST:$NAIS_DATABASE_JITSUTEST_JITSUTEST_PORT/$NAIS_DATABASE_JITSUTEST_JITSUTEST_DATABASE?schema=newjitsu" || echo "Failed to set DATABASE_URL" >> /tmp/run_error.log
  echo "DATABASE_URL set to: $DATABASE_URL"
else
  echo "Error: Missing required database environment variables"
  exit 1
fi

# Start the application
yarn start-docker